export const COUNTRIES = [
  "Kenya",
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Nigeria",
  "South Africa",
  "Uganda",
  "Tanzania",
  "Rwanda",
  "India",
  "United Arab Emirates",
  "Other",
];
